runtime: python312  # Adjust if you use a different Python version 

handlers:
- url: /static/
  static_dir: static
- url: /.*
  script: auto  # Tells App Engine to automatically find your Django WSGI application
